// <auto-generated />
namespace RAD301_January_2022_DataModel_S00197425.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class seedingflightandpassengerdataS00197425 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seedingflightandpassengerdataS00197425));
        
        string IMigrationMetadata.Id
        {
            get { return "202201101822070_seeding-flight-and-passenger-data-S00197425"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
